server:
 port: 8080
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/generator_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true&nullCatalogMeansCurrent=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: 12345678
  username: root

